# Font settings
[font]
  size = 15
  normal.family = "FiraCode Nerd Font"
  bold.family = "FiraCode Nerd Font"
  italic.family = "FiraCode Nerd Font" 
  bold_italic.family = "FiraCode Nerd Font" 

[window]
  opacity = 0.8

[window.padding]
  x = 6  # Horizontal padding
  y = 6  # Vertical padding

[terminal]
  # Shell to execute (required)
  shell = "/bin/zsh"
